@startuml joinWithDuplicate

title Join a game with a duplicate client name

participant "Client 1" as Client1
participant "Server" as Server
participant "Client 2" as Client2

== Join a game ==
Client1->Server: Establish connection
Server-->Client1: Connection established
Client1->Server: JOIN gege 1
Server->Client1: OK

== Join a game with a duplicate client name ==
Client2->Server: Establish connection
Server-->Client2: Connection established
Client2->Server: JOIN gege 0
Server->Client2: ERROR 1

@enduml
