@startuml leaveAGameWithInvalidGameId

title Leave a game with invalid game id

participant "Client 1" as Client1
participant "Server" as Server

== Join a game ==
Client1->Server: Establish connection
Server-->Client1: Connection established
Client1->Server: JOIN gege 0
Server->Client1: OK

== Send a guess too long ==
Client1->Server: LEAVE gege asd
Server-->Client1: ERROR 1

@enduml
